# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Desolation'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["desolation rgbled_adapter"]'
      custom_config: '["#define MIRYOKU_ALPHAS_QWERTY"]'
      branches: '["zmkfirmware/zmk/main"]'
      modules: '["miketronic/zmk-keyboards-desolation/main caksoylar/zmk-rgbled-widget/main"]'
