# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example Lintilla'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["lintilla_left_central rgbled-adapter","lintilla_right_peripheral rgbled_adapter"]'
      custom_config: '["#define MIRYOKU_ALPHAS_QWERTY"]'
      branches: '["zmkfirmware/zmk/main ctranstrum/lintilla/zmk caksoylar/zmk-rgbled-widget/main"]'
      modules: '["caksoylar/zmk-rgbled-widget/main"]'
