# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example Lintilla'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["lintilla_dongle","lintilla_left_peripheral rgbled_adapter","lintilla_left_central rgbled_adapter","lintilla_right_peripheral rgbled_adapter","settings_reset"]'
      custom_config: '["#define MIRYOKU_ALPHAS_QWERTY","#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y"]'
      branches: '["zmkfirmware/zmk/main"]'
      modules: '["petejohanson/zmk/feat/pointers-move-scroll","zmkfirmware/zmk/main petejohanson/zmk/feat/pointers-move-scroll","ctranstrum/lintilla/zmk caksoylar/zmk-rgbled-widget/main"]'
